<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Grandia.Runtime</RootNamespace>
    <AssemblyName>Grandia.Runtime</AssemblyName>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <RollForward>LatestMinor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\sdk\Grandia.Sdk.csproj" />
  </ItemGroup>

</Project>
